version: "3"
services:
  elasticsearch-powerfall-convo:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch-powerfall-convo
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana-powerfall-convo:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana-powerfall-convo
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-powerfall-convo:9200
    ports:
      - 5601:5601
  loader-powerfall-convo:
    build: ./loader
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-powerfall-convo:9200
    depends_on:
      - elasticsearch-powerfall-convo
      - kibana-powerfall-convo
